		CREATE TABLE IF NOT EXISTS `$this->table_name_brewing_fermentables` (
			id     INT UNSIGNED NOT NULL AUTO_INCREMENT,
			name   TINYTEXT NOT NULL,
			country TINYTEXT,
			category TINYTEXT NOT NULL,
			type   TINYTEXT NOT NULL,
			color  DOUBLE  NOT NULL,
			ppg    DOUBLE  NOT NULL,
			UNIQUE KEY id (id)
		); $charset_collate;

		/**
 		**	http://www.brewersfriend.com/fermentables/
		**	https://www.brewtoad.com/generic-fermentables?fermentable_type_id=2
 		**/
		INSERT INTO `$this->table_name_brewing_fermentables` (name,country,category,type,color,ppg) VALUES
			('2-Row','United States','Grain','Base Malt',1,37),
			('6-Row','United States','Grain','Base Malt',1,35),
			('Abbey Malt','German','Grain','Base Malt',17,33),
			('Acidulated Malt','German','Grain','Acidulated Malt',3.4,27),
			('Agave Nectar',NULL,'Sugar','Sugar',40,34),
			('Amber','United Kingdom','Grain','Base Malt',27,32),
			('Apricot',NULL,'Fruit','Fruit',0,4.05),
			('Aromatic','Belgian','Grain','Roasted Malt',38,33),
			('Aromatic Malt','American','Grain','Base Malt',20,35),
			('Ashbourne Mild','American','Grain','Base Malt',5.3,30),
			('Banana',NULL,'Fruit','Fruit',0,7.65),
			('Belgian Candi Sugar - Amber/Brown',NULL,'Sugar','Sugar',60,38),
			('Belgian Candi Sugar - Clear/Blond',NULL,'Sugar','Sugar',0,38),
			('Belgian Candi Sugar - Dark',NULL,'Sugar','Sugar',275,38),
			('Belgian Candi Syrup - Amber',NULL,'Sugar','Sugar',40,32),
			('Belgian Candi Syrup - Clear',NULL,'Sugar','Sugar',0,32),
			('Belgian Candi Syrup - D2',NULL,'Sugar','Sugar',160,32),
			('Belgian Candi Syrup - Dark',NULL,'Sugar','Sugar',80,32),
			('Biscuit','Belgian','Grain','Roasted Malt',23,35),
			('Black Barley','American','Grain','Roasted Malt',530,27),
			('Black Malt','American','Grain','Roasted Malt',500,28),
			('Black Malt','Finland','Grain','Roasted Malt',526,30),
			('Black Patent','United Kingdom','Grain','Roasted Malt',525,27),
			('Blackprinz','American','Grain','Roasted Malt',500,36),
			('Blueberry',NULL,'Fruit','Fruit',0,4.95),
			('Bohemian Pilsner','German','Grain','Base Malt',1.9,38),
			('Bonlander Munich','American','Grain','Base Malt',10,36),
			('Brown','United Kingdom','Grain','Roasted Malt',65,32),
			('Brown Rice Syrup - Gluten Free',NULL,'Sugar','Raw',2,44),
			('Brown Sugar',NULL,'Sugar','Sugar',15,45),
			('Buckwheat Malt - Gluten Free','American','Grain','Gluten-free Malt',2,25),
			('Cane Sugar',NULL,'Sugar','Sugar',0,46),
			('Cara 20L','Belgian','Grain','Crystal Malt',22,34),
			('Cara 45L','Belgian','Grain','Crystal Malt',42,34),
			('Cara Malt','United Kingdom','Grain','Crystal Malt',17.5,35),
			('Cara Pale','Finland','Grain','Crystal Malt',4,35),
			('Cara Plus 100','Finland','Grain','Crystal Malt',38,35),
			('Cara Plus 150','Finland','Grain','Crystal Malt',57,35),
			('Cara Plus 200','Finland','Grain','Crystal Malt',76,35),
			('Cara Plus 250','Finland','Grain','Crystal Malt',94,35),
			('CaraAmber','German','Grain','Crystal Malt',23,34),
			('CaraAroma','German','Grain','Crystal Malt',130,34),
			('CaraBelge','German','Grain','Crystal Malt',13.6,33),
			('CaraBohemian','German','Grain','Crystal Malt',75,33),
			('CaraBrown','American','Grain','Roasted Malt',55,34),
			('CaraCrystal Wheat Malt','American','Grain','Crystal Malt',55,34),
			('Carafa I','German','Grain','Roasted Malt',340,32),
			('Carafa II','German','Grain','Roasted Malt',425,32),
			('Carafa III','German','Grain','Roasted Malt',535,32),
			('CaraFoam','German','Grain','Crystal Malt',1.8,37),
			('CaraHell','German','Grain','Crystal Malt',11,34),
			('Caramel / Crystal 10L','American','Grain','Crystal Malt',10,35),
			('Caramel / Crystal 120L','American','Grain','Crystal Malt',120,33),
			('Caramel / Crystal 150L','American','Grain','Crystal Malt',150,33),
			('Caramel / Crystal 15L','American','Grain','Crystal Malt',15,35),
			('Caramel / Crystal 20L','American','Grain','Crystal Malt',20,35),
			('Caramel / Crystal 30L','American','Grain','Crystal Malt',30,34),
			('Caramel / Crystal 40L','American','Grain','Crystal Malt',40,34),
			('Caramel / Crystal 60L','American','Grain','Crystal Malt',60,34),
			('Caramel / Crystal 75L','American','Grain','Crystal Malt',75,33),
			('Caramel / Crystal 80L','American','Grain','Crystal Malt',80,33),
			('Caramel / Crystal 90L','American','Grain','Crystal Malt',90,33),
			('Caramel Pils','Belgian','Grain','Crystal Malt',8,34),
			('Caramel Pils','German','Grain','Crystal Malt',2.4,35),
			('Caramel Wheat','German','Grain','Crystal Malt',46,34),
			('CaraMunich','Belgian','Grain','Crystal Malt',50,33),
			('CaraMunich I','German','Grain','Crystal Malt',39,34),
			('CaraMunich II','German','Grain','Crystal Malt',46,34),
			('CaraMunich III','German','Grain','Crystal Malt',57,34),
			('Carapils','German','Grain','Crystal Malt',1.3,35),
			('Carapils (Dextrine Malt),','American','Grain','Crystal Malt',1.8,33),
			('CaraRed','German','Grain','Crystal Malt',20,34),
			('Carastan (30/37),','United Kingdom','Grain','Crystal Malt',34,35),
			('Carastan Light (15L),','United Kingdom','Grain','Crystal Malt',15,35),
			('CaraVienne','Belgian','Grain','Crystal Malt',20,34),
			('Cherry',NULL,'Fruit','Fruit',0,6.3),
			('Chocolate(US)','American','Grain','Roasted Malt',350,29),
			('Chocolate(BE)','Belgian','Grain','Roasted Malt',340,30),
			('Chocolate(UK)','United Kingdom','Grain','Roasted Malt',425,34),
			('Chocolate Malt','Finland','Grain','Roasted Malt',338,31),
			('Chocolate Rye','German','Grain','Roasted Malt',240,31),
			('Chocolate Wheat','German','Grain','Roasted Malt',413,31),
			('Coffee Malt','United Kingdom','Grain','Roasted Malt',150,36),
			('Cookie Malt','Finland','Grain','Roasted Malt',19,37),
			('Corn Sugar - Dextrose',NULL,'Sugar','Sugar',0.5,46),
			('Corn Syrup',NULL,'Sugar','Sugar',0.5,37),
			('Cranberry',NULL,'Fruit','Fruit',0,1.8),
			('Crystal 10L Millet Malt - Gluten Free','American','Grain','Gluten-free Malt',10,25),
			('Crystal 140L','United Kingdom','Grain','Crystal Malt',140,33),
			('Crystal 15L','United Kingdom','Grain','Crystal Malt',15,34),
			('Crystal 30L','United Kingdom','Grain','Crystal Malt',30,34),
			('Crystal 30L Millet Malt - Gluten Free','American','Grain','Gluten-free Malt',30,25),
			('Crystal 45L','United Kingdom','Grain','Crystal Malt',45,34),
			('Crystal 50L','United Kingdom','Grain','Crystal Malt',50,34),
			('Crystal 60L','United Kingdom','Grain','Crystal Malt',60,34),
			('Crystal 70L','United Kingdom','Grain','Crystal Malt',70,34),
			('Crystal 90L','United Kingdom','Grain','Crystal Malt',90,33),
			('Crystal Malt 100','Finland','Grain','Crystal Malt',38,35),
			('Crystal Malt 150','Finland','Grain','Crystal Malt',57,35),
			('Crystal Malt 250','Finland','Grain','Crystal Malt',94,35),
			('Crystal Malt 300','Finland','Grain','Crystal Malt',113,35),
			('Crystal Malt 50','Finland','Grain','Crystal Malt',19,35),
			('Crystal Rye','United Kingdom','Grain','Crystal Malt',90,33),
			('Dark Ale','Finland','Grain','Roasted Malt',14,35),
			('Dark Chocolate','American','Grain','Roasted Malt',420,29),
			('Dark Crystal 80L','United Kingdom','Grain','Crystal Malt',80,33),
			('Dark Munich','German','Grain','Base Malt',10,36),
			('Dark Roasted Millet Malt - Gluten Free','American','Grain','Gluten-free Malt',300,25),
			('Dark Wheat','German','Grain','Base Malt',6.5,39),
			('Date',NULL,'Fruit','Fruit',0,27),
			('De-Bittered Black','Belgian','Grain','Roasted Malt',566,34),
			('De-Husked Caraf I','German','Grain','Roasted Malt',340,32),
			('De-Husked Caraf II','German','Grain','Roasted Malt',418,32),
			('De-Husked Caraf III','German','Grain','Roasted Malt',470,32),
			('Demerara (Raw), Sugar',NULL,'Sugar','Sugar',2,46),
			('Dextrine Malt','United Kingdom','Grain','Crystal Malt',1.8,33),
			('Dextrose (Corn Sugar),',NULL,'Sugar','Sugar',0,46),
			('Dry Malt Extract - Amber',NULL,'Dry Extract','Extract',10,42),
			('Dry Malt Extract - Dark',NULL,'Dry Extract','Extract',30,44),
			('Dry Malt Extract - Extra Light',NULL,'Dry Extract','Extract',2.5,42),
			('Dry Malt Extract - Light',NULL,'Dry Extract','Extract',4,42),
			('Dry Malt Extract - Maris Otter',NULL,'Dry Extract','Extract',2,42),
			('Dry Malt Extract - Munich',NULL,'Dry Extract','Extract',8,42),
			('Dry Malt Extract - Pale',NULL,'Dry Extract','Extract',2,42),
			('Dry Malt Extract - Pilsen',NULL,'Dry Extract','Extract',2,42),
			('Dry Malt Extract - Rye',NULL,'Dry Extract','Extract',9,42),
			('Dry Malt Extract - Wheat',NULL,'Dry Extract','Extract',3,42),
			('Enzyme Malt','Finland','Grain','Base Malt',0,35),
			('ESB Malt','Canadian','Grain','Base Malt',3.5,36),
			('Extra Dark Crystal 120L','United Kingdom','Grain','Crystal Malt',120,33),
			('Extra Dark Crystal 160L','United Kingdom','Grain','Crystal Malt',160,33),
			('Flaked Barley',NULL,'Adjunct','Raw',2.2,32),
			('Flaked Corn',NULL,'Adjunct','Raw',0.5,40),
			('Flaked Oats',NULL,'Adjunct','Raw',2.2,33),
			('Flaked Rice',NULL,'Adjunct','Raw',0.5,40),
			('Flaked Rye',NULL,'Adjunct','Raw',2.8,36),
			('Flaked Wheat',NULL,'Adjunct','Raw',2,34),
			('Floor-Malted Bohemian Pilsner','German','Grain','Base Malt',1.8,38),
			('Floor-Malted Bohemian Pilsner Dk','German','Grain','Base Malt',6.5,38),
			('Floor-Malted Bohemian Wheat','German','Grain','Base Malt',2,38),
			('Golden Naked Oats','United Kingdom','Grain','Raw',10,33),
			('Golden Promise','United Kingdom','Grain','Base Malt',3,37),
			('Gooseberry',NULL,'Fruit','Fruit',0,4.95),
			('Grits',NULL,'Adjunct','Raw',1,37),
			('Halcyon','United Kingdom','Grain','Base Malt',2,36),
			('Honey',NULL,'Sugar','Sugar',2,42),
			('Honey (Buckwheat),',NULL,'Sugar','Sugar',2,42),
			('Honey Malt','Canadian','Grain','Base Malt',25,37),
			('Invert Sugar',NULL,'Sugar','Sugar',1,46),
			('Kolsch','German','Grain','Base Malt',2,37),
			('Lactose (Milk Sugar),',NULL,'Sugar','Sugar',1,41),
			('Lager','United Kingdom','Grain','Base Malt',1.4,38),
			('Light Roasted Millet Malt - Gluten Free','American','Grain','Gluten-free Malt',7,25),
			('Lime',NULL,'Fruit','Fruit',0,0.45),
			('Liquid Malt Extract - Amber',NULL,'Liquid Extract','Extract',10,35),
			('Liquid Malt Extract - Dark',NULL,'Liquid Extract','Extract',30,35),
			('Liquid Malt Extract - Extra Light',NULL,'Liquid Extract','Extract',2.5,37),
			('Liquid Malt Extract - Light',NULL,'Liquid Extract','Extract',4,35),
			('Liquid Malt Extract - Maris Otter',NULL,'Liquid Extract','Extract',4,36),
			('Liquid Malt Extract - Munich',NULL,'Liquid Extract','Extract',8,35),
			('Liquid Malt Extract - Pale',NULL,'Liquid Extract','Extract',4,37),
			('Liquid Malt Extract - Pilsen',NULL,'Liquid Extract','Extract',2,35),
			('Liquid Malt Extract - Rye',NULL,'Liquid Extract','Extract',9,36),
			('Liquid Malt Extract - Sorghum',NULL,'Liquid Extract','Extract',2,40),
			('Liquid Malt Extract - Wheat',NULL,'Liquid Extract','Extract',3,35),
			('Malted Naked Oats','United Kingdom','Grain','Base Malt',1.3,33),
			('Maltodextrin',NULL,'Sugar','Sugar',0,39),
			('Mango',NULL,'Fruit','Fruit',0,4.95),
			('Maple Syrup',NULL,'Sugar','Sugar',35,30),
			('Maris Otter Pale','United Kingdom','Grain','Base Malt',3.75,38),
			('Medium Roasted Millet Malt - Gluten Free','American','Grain','Gluten-free Malt',36,25),
			('Melanoid Malt','Finland','Grain','Roasted Malt',27,35),
			('Melanoidin','German','Grain','Roasted Malt',25,37),
			('Midnight Wheat Malt','American','Grain','Roasted Malt',550,33),
			('Mild','United Kingdom','Grain','Base Malt',3,37),
			('Molasses',NULL,'Sugar','Sugar',80,36),
			('Munich(BE)','Belgian','Grain','Base Malt',6,38),
			('Munich(UK)','United Kingdom','Grain','Base Malt',6,37),
			('Munich - 60L','American','Grain','Base Malt',60,33),
			('Munich - Dark 20L','American','Grain','Base Malt',20,33),
			('Munich - Light 10L','American','Grain','Base Malt',10,33),
			('Munich Dark(CA)','Canadian','Grain','Base Malt',32,34),
			('Munich Dark(GR)','German','Grain','Base Malt',15.5,37),
			('Munich Light(CA)','Canadian','Grain','Base Malt',10,34),
			('Munich Light(GR)','German','Grain','Base Malt',6,37),
			('Munich Malt','Finland','Grain','Base Malt',7,36),
			('Munich Millet Malt - Gluten Free','American','Grain','Gluten-free Malt',7,25),
			('Oat Malt','United Kingdom','Grain','Base Malt',2,28),
			('Optic','United Kingdom','Grain','Base Malt',2.1,38),
			('Organic Pilsner Malt','Finland','Grain','Base Malt',2,36),
			('Pale 2-Row(US)','American','Grain','Base Malt',1.8,37),
			('Pale 2-Row(CA)','Canadian','Grain','Base Malt',1.75,36),
			('Pale 2-Row(UK)','United Kingdom','Grain','Base Malt',2.5,38),
			('Pale 2-Row - Toasted','American','Grain','Base Malt',30,33),
			('Pale 6-Row','American','Grain','Base Malt',1.8,35),
			('Pale Ale(US)','American','Grain','Base Malt',3.5,37),
			('Pale Ale(BE)','Belgian','Grain','Base Malt',3.4,38),
			('Pale Ale(GR)','German','Grain','Base Malt',2.3,39),
			('Pale Ale Malt','Finland','Grain','Base Malt',2,36),
			('Pale Chocolate','United Kingdom','Grain','Roasted Malt',207,33),
			('Pale Millet Malt - Gluten Free','American','Grain','Gluten-free Malt',1.5,30),
			('Pale Wheat(CA)','Canadian','Grain','Base Malt',2,36),
			('Pale Wheat(GR)','German','Grain','Base Malt',1.5,39),
			('Peach',NULL,'Fruit','Fruit',0,4.05),
			('Pear',NULL,'Fruit','Fruit',0,4.5),
			('Pearl','United Kingdom','Grain','Base Malt',2.1,37),
			('Peated Malt','United Kingdom','Grain','Base Malt',2.5,38),
			('Pilsen','United Kingdom','Grain','Base Malt',1.8,36),
			('Pilsner(US)','American','Grain','Base Malt',1.8,37),
			('Pilsner(BE)','Belgian','Grain','Base Malt',1.6,37),
			('Pilsner(GR)','German','Grain','Base Malt',1.6,38),
			('Pilsner Malt','Finland','Grain','Base Malt',2,37),
			('Pineapple',NULL,'Fruit','Fruit',0,5.85),
			('Plum',NULL,'Fruit','Fruit',0,4.95),
			('Raspberry',NULL,'Fruit','Fruit',0,3.15),
			('Red Wheat','American','Grain','Base Malt',2.5,38),
			('Red X','German','Grain','Base Malt',12,36),
			('Rice Hulls',NULL,'Adjunct','Other',0,0),
			('Rice Syrup Solids',NULL,'Dry Extract','Raw',1,37),
			('Roasted Barley(US)','American','Grain','Roasted Malt',300,33),
			('Roasted Barley(BE)','Belgian','Grain','Roasted Malt',575,30),
			('Roasted Barley(UK)','United Kingdom','Grain','Roasted Malt',550,29),
			('Rolled Oats',NULL,'Adjunct','Raw',2.2,33),
			('Rye(US)','American','Grain','Base Malt',3.5,38),
			('Rye(GR)','German','Grain','Base Malt',3.5,38),
			('Smoked Malt(US)','American','Grain','Base Malt',5,37),
			('Smoked Malt(GR)','German','Grain','Base Malt',3,37),
			('Soft Candi Sugar - Blond',NULL,'Sugar','Sugar',5,38),
			('Soft Candi Sugar - Brown',NULL,'Sugar','Sugar',60,38),
			('Special B','Belgian','Grain','Roasted Malt',115,34),
			('Special Roast','American','Grain','Roasted Malt',50,33),
			('Spelt Malt','German','Grain','Base Malt',2,37),
			('Strawberry',NULL,'Fruit','Fruit',0,3.15),
			('Torrified Barley',NULL,'Adjunct','Raw',2,36),
			('Torrified Wheat',NULL,'Adjunct','Raw',2,36),
			('Turbinado',NULL,'Sugar','Sugar',10,44),
			('UnMalted Wheat','Belgian','Grain','Raw',2,36),
			('Victory','American','Grain','Roasted Malt',28,34),
			('Vienna(US)','American','Grain','Base Malt',4,35),
			('Vienna(GR)','German','Grain','Base Malt',4,37),
			('Vienna Malt','Finland','Grain','Base Malt',3,36),
			('Watermelon',NULL,'Fruit','Fruit',0,4.05),
			('Wheat(US)','American','Grain','Base Malt',1.8,38),
			('Wheat(BE)','Belgian','Grain','Base Malt',1.8,38),
			('Wheat(UK)','United Kingdom','Grain','Base Malt',2,37),
			('Wheat Malt(GR)','German','Grain','Base Malt',2,37),
			('Wheat Malt(FL)','Finland','Grain','Base Malt',2,38),
			('White Sorghum Syrup - Gluten Free',NULL,'Sugar','Sugar',1.5,44),
			('White Wheat','American','Grain','Base Malt',2.8,40);